{
  "formatVersion": "1.1",
  "component": {
    "group": "com.caldremch.android",
    "module": "service-core",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-milestone-3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "service-core-1.0.0.jar",
          "url": "service-core-1.0.0.jar",
          "size": 7659,
          "sha512": "27a9a4d2a65312015ae30957cd5a288b66ec3cc9deb384ee7de9e67019a9dfb1d2b65916639bd53e0511f02da438c62627ad662dba395aac53fbedaa6099bdb7",
          "sha256": "adaf4a39acf1e047af4b391bed66ef8b5e320ae181eeb8719b9aa1abfc932480",
          "sha1": "498ce5317e3a7a6864c9e833ff6c78c3e3e13115",
          "md5": "dcb86e5770c9804537d985f4fe6bf7f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.caldremch.android",
          "module": "plugin-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "service-core-1.0.0.jar",
          "url": "service-core-1.0.0.jar",
          "size": 7659,
          "sha512": "27a9a4d2a65312015ae30957cd5a288b66ec3cc9deb384ee7de9e67019a9dfb1d2b65916639bd53e0511f02da438c62627ad662dba395aac53fbedaa6099bdb7",
          "sha256": "adaf4a39acf1e047af4b391bed66ef8b5e320ae181eeb8719b9aa1abfc932480",
          "sha1": "498ce5317e3a7a6864c9e833ff6c78c3e3e13115",
          "md5": "dcb86e5770c9804537d985f4fe6bf7f8"
        }
      ]
    }
  ]
}
